CREATE TABLE IF NOT EXISTS "Испытания" (
	"id" SERIAL PRIMARY KEY,
	"испытание" INTEGER NOT NULL REFERENCES "Набор_испытаний"("id") ON DELETE CASCADE ON UPDATE CASCADE,
	"изделие" INTEGER NOT NULL REFERENCES "Выпускаемые_изделия"("id") ON DELETE CASCADE ON UPDATE CASCADE,
	"дата" DATE NOT NULL CHECK ("дата" <= CURRENT_DATE),
	"испытатель" INTEGER NOT NULL REFERENCES "Испытатели"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
	"оборудование" INTEGER NOT NULL REFERENCES "Испытательное_оборудование"("id") ON DELETE RESTRICT ON UPDATE CASCADE
);