CREATE TABLE IF NOT EXISTS "Цеха" (
	"id" SERIAL PRIMARY KEY,
	"название" VARCHAR(255) UNIQUE,
	"начальник_цеха" INTEGER NOT NULL REFERENCES "ИТ_персонал"("id") ON DELETE RESTRICT ON UPDATE CASCADE
);