<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DiningPhilosophers.App.Shared\DiningPhilosophers.App.Shared.csproj" />
    <ProjectReference Include="..\DiningPhilosophers.Simulator\DiningPhilosophers.Simulator.csproj" />
    <ProjectReference Include="..\DiningPhilosophers.Simulator.Concurrent\DiningPhilosophers.Simulator.Concurrent.csproj" />
  </ItemGroup>
  <ItemGroup>
    <!-- Use local names.txt instead of linked from App -->
    <None Remove="..\DiningPhilosophers.App\names.txt" />
    <Content Include="names.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
