name: Test ssh CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
    - name: Debug secrets
      run: |
        echo "User: ${{ secrets.SERVER_USER }}"
        echo "Host: ${{ secrets.SERVER_HOST }}"
        echo "Password length: ${#SSH_PASSWORD}"
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
    - name: Test SSH connection
      run: | 
        ssh -i ~/.ssh/id_ed25519 ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "echo 'SSH works!'"
    
